# Generated by Django 5.0.2 on 2024-04-21 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reaction',
            name='disliked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='liked',
            field=models.BooleanField(default=False),
        ),
    ]
