# Generated by Django 5.0.2 on 2024-04-22 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_reaction_disliked_alter_reaction_liked'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['-is_featured', '-created_at']},
        ),
        migrations.AddField(
            model_name='image',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='is featured'),
        ),
    ]
