# Generated by Django 5.0.2 on 2024-04-02 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0002_room_name_alter_message_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='uid',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
